# The "display name", shown in the GitHub UI
name: Build and test

# Trigger, run on push on any branch
on:
  push:

jobs:
  test: # The 'build' job
    name: "Build application"
    runs-on: "ubuntu-latest"
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Install go 1.21
      - name: Setup go
        uses: actions/setup-go@v4
        with: # Specify input variables to the action
          go-version: "1.21.x"

      # Shell script to print the version
      - run: go version
